#!/bin/bash  
#this script is used to get tcp and udp connetion status  
#tcp status
  
case $1 in  
   closed) 
		  output=`ss -ant|awk '{++S[$1]}END{for(a in S) print a,S[a]}'|awk '/CLOSED/{print $2}'`
          if [ "$output" == "" ];then  
             echo 0  
          else  
             echo $output  
          fi  
        ;;  
   listen)  
		  output=`ss -ant|awk '{++S[$1]}END{for(a in S) print a,S[a]}'|awk '/LISTEN/{print $2}'`
          if [ "$output" == "" ];then  
             echo 0  
          else  
             echo $output  
          fi  
        ;;  
   synrecv)  
		  output=`ss -ant|awk '{++S[$1]}END{for(a in S) print a,S[a]}'|awk '/SYN_RECV/{print $2}'`
          if [ "$output" == "" ];then  
             echo 0  
          else  
             echo $output  
          fi  
        ;;  
   synsent)
          output=`ss -ant|awk '{++S[$1]}END{for(a in S) print a,S[a]}'|awk '/SYN_SENT/{print $2}'`		  
          if [ "$output" == "" ];then  
             echo 0  
          else  
             echo $output  
          fi  
        ;;  
   established)  
          output=`ss -ant|awk '{++S[$1]}END{for(a in S) print a,S[a]}'|awk '/ESTAB/{print $2}'`		  
          if [ "$output" == "" ];then  
             echo 0  
          else  
             echo $output  
          fi  
        ;;  
   timewait) 
          output=`ss -ant|awk '{++S[$1]}END{for(a in S) print a,S[a]}'|awk '/TIME_WAIT/{print $2}'`		  
          if [ "$output" == "" ];then  
             echo 0  
          else  
             echo $output  
          fi  
        ;;  
   closing)  
          output=`ss -ant|awk '{++S[$1]}END{for(a in S) print a,S[a]}'|awk '/CLOSING/{print $2}'`		  
          if [ "$output" == "" ];then  
             echo 0  
          else  
             echo $output  
          fi  
        ;;  
   closewait) 
          output=`ss -ant|awk '{++S[$1]}END{for(a in S) print a,S[a]}'|awk '/CLOSE_WAIT/{print $2}'`		  
          if [ "$output" == "" ];then  
             echo 0  
          else  
             echo $output  
          fi  
        ;;  
   lastack)    
		  output=`ss -ant|awk '{++S[$1]}END{for(a in S) print a,S[a]}'|awk '/LAST_ACK/{print $2}'`
          if [ "$output" == "" ];then  
             echo 0  
          else  
             echo $output  
          fi  
         ;;  
   finwait1)  
          output=`ss -ant|awk '{++S[$1]}END{for(a in S) print a,S[a]}'|awk '/FIN_WAIT1/{print $2}'`		  
          if [ "$output" == "" ];then  
             echo 0  
          else  
             echo $output  
          fi  
         ;;  
   finwait2)   
          output=`ss -ant|awk '{++S[$1]}END{for(a in S) print a,S[a]}'|awk '/FIN_WAIT2/{print $2}'`		  
          if [ "$output" == "" ];then  
             echo 0  
          else  
             echo $output  
          fi  
         ;;  
         *)  
          echo -e "\e[033mUsage: sh  $0 [closed|closing|closewait|synrecv|synsent|finwait1|finwait2|listen|established|lastack|timewait]\e[0m"  
esac
